//
//  CurrentUser.swift
//  OnTheMap
//
//  Created by Steven O'Toole on 4/16/15.
//  Copyright (c) 2015 Steven O'Toole. All rights reserved.
//

import Foundation
import MapKit

class CurrentUser {
    var sessionID: String = ""
    var objectID: String = ""       // generated by Parse
    var createdAt: String = ""      // generated by Parse

    var userKey: String = ""      // map to uniqueKey in Parse

    var firstName: String = ""
    var lastName: String = ""
    var email: String = ""        // not used

    var mediaURL: String = ""
    var mapString: String = ""

    var latitude: CLLocationDegrees = 0.0
    var longitude: CLLocationDegrees = 0.0


    var encodedForHTTPBody: String {
        return "{" +
            "\"uniqueKey\": \"\(userKey)\"" + ", " +
            "\"firstName\": \"\(firstName)\"" + ", " +
            "\"lastName\": \"\(lastName)\"" + ", " +
            "\"mapString\": \"\(mapString)\"" + ", " +
            "\"mediaURL\": \"\(mediaURL)\"" + ", " +
            "\"latitude\": \(latitude)" + ", " +
            "\"longitude\": \(longitude)" + "}"
    }

    func loadPublicData(dictionary: [String: AnyObject]) {

        if let last = dictionary["last_name"] as? String {
            self.lastName =  last
        }
        if let first = dictionary["first_name"] as? String {
            self.firstName = first
        }
        if let emailDict = dictionary["email"] as? NSDictionary,
            let addr = dictionary["address"] as? String {
            self.email = addr
        }
    }

    // Optional({"createdAt":"2015-04-27T20:53:00.872Z","objectId":"i3f1ijVWtO"})

    func updateAfterSave(dictionary: [String: AnyObject]) {
        if let objectID = dictionary["objectId"] as? String {
            self.objectID = objectID
        }
        if let createdAt = dictionary["createdAt"] as? String {
            self.createdAt = createdAt
        }
     }

}